name: Update CG Manifest

on:
  repository_dispatch:

jobs:
  cgmanifest:
    name: Generate cgmanifest.json
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Automated update') && !contains(github.event.head_commit.message, 'CI ignore')"
    steps:

    - name: Free more space
      id: free_space 
      run: |
        set -e
        # Ensure enough space is available for build
        sudo apt-get autoremove -y
        sudo apt-get clean -y
        sudo rm -rf /usr/share/dotnet

    - name: Checkout
      id: checkout
      uses: actions/checkout@v1

    - name: Azure CLI login
      id: az_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_ACR_CREDS }}

    - name: Update CG Manifest
      id: update_cg_manifest
      run: |
        set -e

        # Ensure enough space is available for build
        sudo apt-get autoremove -y
        sudo apt-get clean -y
        sudo rm -rf /usr/share/dotnet

        # ACR login
        ACR_REGISTRY_NAME=$(echo ${{ secrets.REGISTRY }} | grep -oP '(.+)(?=\.azurecr\.io)')
        az acr login --name $ACR_REGISTRY_NAME

        # Pull images and update cgmanifest.json
        yarn install
        GIT_BRANCH=$(echo "${{ github.ref }}" | grep -oP 'refs/(heads|tags)/\K(.+)')
        if [ "$GIT_BRANCH" == "" ]; then 
            GIT_BRANCH=master
        fi
        build/vscdc cg  --no-build \
                        --release $GIT_BRANCH \
                        --github-repo ${{ github.repository }} \
                        --registry ${{ secrets.REGISTRY }} \
                        --registry-path ${{ secrets.REGISTRY_BASE_PATH }}

        # Push updated cgmnaifest.json to source control
        git config --global user.email "vscr-feedback@microsoft.com"
        git config --global user.name "CI"
        git add cgmanifest.json
        git commit -m 'Automated update for CG' \
          && git push "https://ci:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" "HEAD:${{ github.ref }}" \
          || echo 'No updates to cgmanifest.json'
