name: CI & Push "dev"

on: 
  push:
    branches: master

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:

    - name: Container Registry Login
      id: docker_login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Checkout
      id: checkout
      uses: actions/checkout@v1
      
    - name: Push "dev" and Test Packaging
      run: |
        # Push dev images and package
        set -e
        yarn install
        build/vscdc pack --release master --github-repo ${{ github.repository }} --registry ${{ secrets.REGISTRY }} --registry-path ${{ secrets.REGISTRY_BASE_PATH }} --stub-registry ${{ secrets.STUB_REGISTRY }} --stub-registry-path ${{ secrets.STUB_REGISTRY_BASE_PATH }}
        mv ./vscode-dev-containers-*.tgz ./vscode-dev-containers-${{ github.sha }}.tgz

    - name: Upload Package
      uses: actions/upload-artifact@v1.0.0
      with:
        name: vscode-dev-containers-${{ github.sha }}.tgz
        path: ./vscode-dev-containers-${{ github.sha }}.tgz
