name: Troubleshooting

on: 
  push:
    branches: [ci-troubleshooting]

jobs:
  troubleshooting:
    name: Troubleshooting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v1
           
    - name: Run troubleshooting script
      id: troubleshooting_script
      run: |
        set -e

        # Prep test
        export SVC_PRN=$(node -e 'console.log(JSON.parse(`${{ secrets.AZ_ACR_CREDS }}`).clientId)')
        export PRN_SECRET=$(node -e 'console.log(JSON.parse(`${{ secrets.AZ_ACR_CREDS }}`).clientSecret)')
        export TENANT=$(node -e 'console.log(JSON.parse(`${{ secrets.AZ_ACR_CREDS }}`).tenantId)')
        export SUB=$(node -e 'console.log(JSON.parse(`${{ secrets.AZ_ACR_CREDS }}`).subscriptionId)')

        # Run test
        echo Logging in...
        az login --service-principal -u $SVC_PRN -p $PRN_SECRET --tenant $TENANT
        echo Show account..
        az account show
        echo Account list...
        az account list --refresh
        echo Setting subscription...
        az account set --subscription $SUB
        echo ACR login...
        az acr login --name devcon
